[package]
name = "rusty_bedtime_timer"
version = "0.1.0"
edition = "2024"

[dependencies]
# For date and time calculations
chrono = "0.4"
# For sending the Ubuntu system notification
notify-rust = "4.11"